### ISSUE TITLE
Apple Store application

### ISSUE THREAD

**Issue by nrm83** [ilcato/FibaroHomeKitTool#1]
The Ilcato Toolkit will be remove of Itune? I can't found it ?

regards,

**Comment by ilcato** [comment]
I didn't renewed the Apple Development program.

**Comment by nrm83** [comment]
Ok, can I install manually on Iphone or not ?

**Comment by ilcato** [comment]
If you look at my GitHub account you will find the source project that can be compiled and installed manually.

**Comment by nrm83** [comment]
Ok
