### ISSUE TITLE
IOS App not avalaible

### ISSUE THREAD

**Issue by macmonty** [ilcato/FibaroHomeKitTool#2]
Hello the IOS app on the Apple Store are unavalaible, tested on USA and Spain store, how i can install in my iphone,

Thanks

**Comment by ilcato** [comment]
Use Xcode to compile project and install on your phone.
I removed it from the app store because of the developer licence costs.

**Comment by macmonty** [comment]
What version of the Xcode its the right version to compile it? Testet on the latest with errors

Thanks

**Comment by ilcato** [comment]
I renewed the developer licence. The app should be available again soon.
